---
title: "Assignment 1 - Introduction Video"
subtitle: "Due Friday, July 11th at 11:59 pm"
---

::: callout-important
Assignments are posted in myCourses. Please submit your work there.
:::

## Description

For this assignment, you will be asked to create a video introducing yourself to the instructor. I know that it can be really awkward to just talk to your computer, so you will only be required to be on camera when introducing yourself. This is an opportunity for me to get to know you as well as needing to meet the RIT requirement for online courses.

**Points: 20**

## Guidelines

Create a brief video (under 5 minutes is fine) that includes your answers to the following questions:

1.  Your Name
2.  Your Pronouns
3.  Your Major
4.  What is a TV show, movie, book or album that you have recently watched/read/listened to that you really enjoyed?
5.  What is the most boring thing about you?
6.  What is something that you would like the professor to know about you?

The video can be done through Zoom or any other recording platform. The expectations are that you are on camera stating your name, and that you answer the questions above (but the rest of the questions you don't have to be seen if you don't want to). If you would like to have a short PowerPoint, or other supporting materials, please do so.

**Upload to myCourses by deadline**
