---
title: Syllabus
---

## **Intro to Psychology (Online Asynchronous)**

|                |                                      |
|----------------|--------------------------------------|
| **Professor**  | Dustin Haraden, PhD                  |
| *Email/Office* | dxhgsh\@rit.edu; Eastman Hall - 3378 |
| *Office Hours* | By Appointment                       |
| *Class Times*  | Asynchronous                         |

For a PDF copy of the syllabus: [Download File](/files/PSYC101_Syllabus.pdf)

### **Course Overview**

This course offers a broad introduction to the field of Psychology, covering various sub-disciplines and emphasizing the scientific study of behavior and cognition. Students will gain a solid understanding of the scientific process, major psychological theories, and the correct usage of psychological terminology. The curriculum fosters critical evaluation skills for examining psychological research findings and highlights practical applications of psychological concepts in daily life. Emphasizing contemporary insights, the course focuses on the scientific method in measuring human behavior, with a student-centric approach that encourages active engagement and self-knowledge.

------------------------------------------------------------------------

### **Required Materials**

**Textbook**: We will an open source (this means free) textbook throughout the semester. The link to the textbook is included below. A PDF version of the text is uploaded to myCourses.  

Spielman, R. M., Jenkins, W., & Lovett, M. (2020). Psychology 2e. <https://openstax.org/details/books/psychology-2e>

**Other Required Readings**: All additional readings (if necessary) will be posted to the course website.

------------------------------------------------------------------------

### **Weekly Schedule & Topics**

***Note:*** *This is subject to change. Students will be notified immediately of any changes or updates.*

Below you will find an outline for the course, with a rough outline of dates for each of the units. For specific due dates, please refer to myCourses and/or the [schedule page](/index). All rubrics for assignments will be posted to myCourses as well as on this website.

#### Module 1

-   **Read**: OpenStax Ch. 1, 2 & 3 (Psychological Research, Biopsychology)
-   **Watch**:
    -   Introductory lecture
    -   What is Psychology Research?
    -   Biopsychology
-   **Assignments**:
    -   Introduction Video
    -   Syllabus Quiz
    -   Content Quiz 1

#### Module 2

-   **Read**: OpenStax Ch. 4 & 5 (Consciousness, Sensation/Perception)
-   **Watch**:
    -   Sleep & Circadian Rhythms
    -   Sensation/Perception
-   **Assignments**:
    -   Content Quiz 2
    -   Sleep Journal (3 day minimum + Reflection)

#### Module 3

-   **Read**: OpenStax Ch. 6, 7, 8 (Learning, Memory, Cognition)
-   **Watch**:
    -   Classical Conditioning vs. Operant Conditioning
    -   Memory
-   **Assignments**:
    -   Content Quiz 3
    -   Mini-Experiment Reflection (e.g., shape your behavior with reinforcement)

#### Module 4

-   **Read**: OpenStax Ch. 9 & 10 (Emotion, Motivation, Development)
-   **Watch**:
    -   Emotions/Motivation
    -   Development
-   **Assignments**:
    -   Content Quiz 4
    -   Development in the Media

#### Module 5

-   **Read**: OpenStax Ch. 11 & 12 (Personality, Social Psychology)
-   **Watch**:
    -   Personality - Classification
-   **Assignments**:
    -   Content Quiz 5
    -   Personality Test Drive

#### Module 6

-   **Read**: OpenStax Ch. 15 & 16 (Psych Disorders, Therapy & Treatment) + science vs. pseudoscience resources
-   **Watch**:
    -   Psych Disorders
    -   Therapy
-   **Assignments**:
    -   Content Quiz 6

#### **Final Project Options (Choose One)**

1.  **Podcast Episode:** Explain a psychological concept with examples.
2.  **Infographic:** Visually explain a major topic (e.g., stages of sleep, types of memory).
3.  **Short Paper:** Analyze a psychological issue or concept.
4.  **Public Service Announcement:** Educate others on a disorder or mental health topic.

------------------------------------------------------------------------

### **Evaluation & Grading**

+---------------------------------+----------------+----------------+
| Assignment Type                 | Points         | \% of Grade    |
+=================================+================+================+
| Intro Video & Syllabus Quiz     | 40             | 10%            |
+---------------------------------+----------------+----------------+
| Quizzes (6) - lowest dropped    | 125            | 35%            |
+---------------------------------+----------------+----------------+
| Unit Activities (4)             | 140            | 35%            |
+---------------------------------+----------------+----------------+
| Discussion Post & Reply         | 20             | 5%             |
+---------------------------------+----------------+----------------+
| Final Project                   | 60             | 15%            |
+---------------------------------+----------------+----------------+
| SONA Credits (8 credits)        | \-             | \-             |
+---------------------------------+----------------+----------------+
| **Total**                       | **385**        | **100%**       |
+---------------------------------+----------------+----------------+

*Failure to complete all 8 SONA credits leads to a reduction of final grade by 3.3%*

#### Introduction Video & Syllabus Quiz

With the online, asynchronous structure of the course it can be challenging to have a sense of connection. I will ask each student to create a brief video introducing themselves (rubric will be posted). These will only be seen by the instructor. This introduction is a requirement by RIT for online courses as we need to confirm you are who you say you are (but I also want to get to know my students).

During the first unit, you will also need to complete a brief quiz on the syllabus. You will be allowed to take the quiz as many times as you need to in order to receive the full credit. I want you to be aware of the policies in the course.

#### **Quizzes**

To help solidify the material and identify areas that you can focus your study, there will be regular quizzes consisting of multiple choice and short answer questions. These will be posted to myCourses and can be taken at any point prior to the deadline. All quizzes will become available at the beginning of the semester. There will be 25 multiple choice questions that will be taken mainly from the readings. Each quiz time limit will be 30 minutes. The quizzes will only cover the information from that specific topic (i.e., non-cumulative). Quizzes will be open-note. Lowest quiz grade will automatically be dropped.

#### **Unit Activities**

The assignments for this class will consist of utilizing your knowledge of the topic and applying it to various examples in the real world. Each assignment will be related to a topic in the course, but will also allow you to incorporate information across multiple topics. The assignments will have different structures with some consisting inf written responses and others to incorporate other creative components. The goal of the assignments is to move beyond the textbook and classroom to investigate the application of psychology and to think like a psychologist.

#### Discussions

To help bring the discussion beyond the class, there will be the expectation that you will create and engage with discussion posts (Minimum of 1 created & 1 response). The posts will focus on an area of psychology that is of interest to you. The goal of these posts is for you to share information that you have gathered from elsewhere and bring in to provide some additional information. Topics of these discussions may vary from examining the science behind pop-science articles, reflecting on reading a scientific study, identifying a popular myth in psychology and describing why it is a myth. More information will be available on myCourses/course site to highlight the specific content and expectations.

*Discussion posts and replies must be completed prior to deadline (7/25/25 at 11:59pm)*

#### Final Project

The course will culminate in a final project that will be completed individually. You have the ability to choose the type of project you would like to complete. I want this to be a time for you to bring in any other creative elements that you would like. If you have other ideas for a type of project, please let me know. I am happy to update to accommodate your ideas if they continue to fit the expectations of the project. More information will be provided.

#### SONA Participation

+-----------------------------------------------------------------------------+
| **Useful info**                                                             |
|                                                                             |
| SONA Director: Dr. Dustin Haraden                                           |
|                                                                             |
| Email: [sona\@rit.edu](mailto:sona@rit.edu)                                 |
|                                                                             |
| Information website (for more guidance): <https://ritpsych.github.io/sona/> |
|                                                                             |
| Sona website (for signing up for studies): <https://rit.sona-systems.com>   |
+-----------------------------------------------------------------------------+

Every PSYC101 student must earn **8 Sona credits**. You earn 1 credit per 15 minutes of participation, plus a bonus credit for face-to-face studies, so this will take you a maximum of 2 hours to complete. To earn Sona credits, you must sign up for studies through the psychology department’s Sona website. Other research will not qualify.

\
Your participation must be complete by **5pm on the last day of classes (i.e., the day before Reading Day)**. At that time, if you have NOT earned at least 8 credits, your final grade will be dropped by one “step” – that is, from A to A-, from B- to C+, or from D to F. There is no partial credit and there are no exceptions.

**Grade Scheme**

|   Grade    |  A  |  A-   |  B+   |   B   |  B-   |  C+   |   C   |  C-   |   D   |  F   |
|:----------:|:---:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:----:|
| Percentage | 93+ | 90-92 | 87-89 | 83-86 | 80-82 | 77-79 | 73-76 | 70-72 | 60-69 | \<60 |

------------------------------------------------------------------------

### **Course Policies**

#### Late Policy

> *“A Wizard is never late, nor are they early. They arrive precisely when they mean to.”* 🧙‍♂️

Thanks Gandalf. Super helpful. Unfortunately, we are not wizards and late penalties will be applied to work that is not on time. Due to the accelerated nature of the course, the late penalty will be more severe. There will be a 50% deduction on the first day. Work will not be accepted beyond 24 hours after the deadline.

#### Statement on Reasonable Accommodations

RIT is committed to providing academic adjustments to students with disabilities. If you would like to request academic adjustments such as testing modifications due to a disability, please contact the Disability Services Office. Contact information for the DSO and information about how to request adjustments can be found at [www.rit.edu/dso](http://www.rit.edu/dso). After you receive academic adjustment approval, it is imperative that you contact me as early as possible so that we can work out whatever arrangement is necessary.

#### **Mandatory Reporting**

As an instructor, I have a mandatory reporting responsibility as a part of my role. It is my goal that you feel comfortable sharing information related to your life experiences in classroom discussions, in your written work, and in our one-on-one meetings. I will seek to keep the information you share private to the greatest extent possible. However, I am required to report information I receive regarding sexual misconduct or information about a crime that may have occurred during your time at RIT. 

#### Statement on Title IX

RIT is committed to providing a safe learning environment, free of harassment and discrimination as articulated in our university policies located on our governance website. RIT’s policies require faculty to share information about incidents of gender-based discrimination and harassment with RIT’s Title IX coordinator or deputy coordinators when incidents are stated to them directly. The information you provide to a non-confidential resource which includes faculty will be relayed only as necessary for the Title IX Coordinator to investigate and/or seek resolution. Even RIT Offices and employees who cannot guarantee confidentiality will maintain your privacy to the greatest extent possible.

If an individual discloses information during a public awareness event, a protest, during a class project, or advocacy event, RIT is not obligated to investigate based on this public disclosure. RIT may however use this information to further educate faculty, staff and students about prevention efforts and available resources.

If you would like to report an incident of gender based discrimination or harassment directly you may do so by using the online Sexual Harassment, Discrimination and Sexual Misconduct Reporting or anonymously by using the Compliance and Ethics Hotline. If you have a concern related to gender-based discrimination and/or harassment and prefer to have a confidential discussion, assistance is available from any of RIT’s confidential resources (listed below).

-   RIT Counseling and Psychological Services
    -   585-475-2261 (V)
    -   585-475-6897 (TTY)
    -   www.rit.edu/counseling
-   NTID Counseling and Academic Advising
    -   585-475-6400
    -   www.ntid.rit.edu/counselingdept
-   RIT Student Health Center
    -   585-475-2255 (V)
    -   www.rit.edu/studentaffairs/studenthealth
-   Center for Religious Life
    -   585-475-2137
    -   www.rit.edu/studentaffairs/religion
-   RIT Ombuds Office
    -   585-475-7357
    -   585-475-6424
    -   585-286-4677 (VP)
    -   www.rit.edu/ombuds/contact-us

#### Academic Integrity Statement

As an institution of higher learning, RIT expects students to behave honestly and ethically at all times, especially when submitting work for evaluation in conjunction with any course or degree requirement. The Department of Psychology encourages all students to become familiar with the [RIT Honor Code](https://www.rit.edu/academicaffairs/policiesmanual/p030) and with [RIT's Academic Integrity Policy](https://www.rit.edu/academicaffairs/policiesmanual/d080). RIT’s policy on academic integrity requires the instructor to investigate of any suspected breach of academic integrity. If the preponderance of evidence indicates a breach of academic integrity, the student who did so may incur a consequence up to and including failure for the entire course.

*About Generative AI*

Each course that you are involved in will have differing opinions and goals regarding generative AI (i.e., ChatGPT, Gemini, Perplexity, Claude, etc.). In this course you are allowed to use these as a tool. You can use prompts such as “Teach me about (insert psych topic here) and give me an example that might apply to me.” If you do use generative AI, I would like for you to disclose that information just so I can have a sense of how it is being used. If I suspect that the work that you have turned in is using AI, we will have to have a conversation to determine the next steps. Turning in AI work is considered plagiarism, and you may be asked to re-do the assignment, or possibly receive a 0 on the assignment.

#### RIT COVID-19 Safety Plans

RIT is committed to the safety of the RIT community and beyond. Because the situation is still in a rapid state of change, checking the RIT Ready website, and specifically the RIT Safety Plan for the most up to date information is recommended: <https://www.rit.edu/ready/rit-safety-plan>.

#### Changes to the Syllabus

I have provided this syllabus as a guide to our course and have made every attempt to provide an accurate overview of the course. However, as instructor, I reserve the right to modify this document during the semester, if necessary, to ensure that we achieve course learning objectives. You will receive advance notice of any changes to the syllabus through myCourses/email.
